all:
  hosts:
    master:
      ansible_host: pi1
  children:
    worker_nodes:
      hosts:
        pi2:
          etcd_cluster: true
        pi3:
          etcd_cluster: true
        pi4:
  vars:
    ansible_user: pi