- name: Setup required tools for a base kubernetes node
  hosts: all
  become: yes
  roles:
    - docker
    - etcd
    - flannel
    - docker-with-flannel
    - ca
    - kube-node

- name: Setup worker nodes
  hosts: worker_nodes
  become: yes
  vars:
    master_ip: "{{ hostvars['master'].ansible_default_ipv4.address }}"
  roles:
    - kube-worker

- name: Setup master node
  hosts: master
  become: yes
  roles:
    - kube-master

- hosts: all
  become: yes
  tasks:
  - name: Reboot all cluster nodes
    reboot:
      pre_reboot_delay: 60

- hosts: master
  become: yes
  tasks:
  - name: Wait for all workers to join
    shell: kubectl get nodes | grep Ready
    register: workers_out
    until: workers_out.stdout_lines | length == groups['all'] | length
    retries: 30
    delay: 10
    changed_when: false