- name: Setup required tools for a base kubernetes node
  hosts: all
  become: yes
  roles:
    - docker
    - etcd
    - flannel
    - docker-with-flannel
    - ca
    - kube-node

- name: Setup worker nodes
  hosts: worker_nodes
  become: yes
  roles:
    - kube-worker

- name: Setup master node
  hosts: master
  become: yes
  roles:
    - kube-master

- name: Reboot all cluster nodes
  hosts: all
  become: yes
  roles:
    - reboot

- name: Configure the cluster
  hosts: master
  become: yes
  roles:
    - kube-cluster-config
    - kube-dns