- name: Configure master node
  hosts: master
  become: yes
  tasks:
    - name: Avoid scheduling pods on master node
      shell: kubectl taint nodes {{ ansible_hostname }} node-role.kubernetes.io/master=true:PreferNoSchedule
      ignore_errors: yes

- name: Setup dns addon
  hosts: master
  become: yes
  roles:
    - kube-dns

- name: Setup docker registry addon
  hosts: all
  become: yes
  roles:
    - kube-registry