- when: inventory_hostname  == "master"
  block:
  - name: Generate CA private key and root certificate
    command: openssl req -newkey rsa -nodes -keyout private/ca.key -x509 -subj "/CN={{ ansible_default_ipv4.address }}" -days 10000 -out certs/ca.crt
    args:
      chdir: /etc/ssl
      creates: certs/ca.crt

  - name: Fetch root certificate
    fetch:
      src: /etc/ssl/certs/ca.crt
      dest: /tmp/kube_ca.crt
      flat: true

- name: Transfer root certificate
  copy:
    src: /tmp/kube_ca.crt
    dest: /usr/local/share/ca-certificates/ca.crt

- name: Install the certificate
  command: update-ca-certificates
  register: install_result
  changed_when: "'0 added, 0 removed' not in install_result.stdout"