- name: Copy binaries
  copy: 
    src: "{{ item }}"
    dest: /usr/bin
    mode: 0755
  with_items:
    - downloads/etcd
    - downloads/etcdctl

- name: Add systemd service
  template: 
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: 0644

- name: Enable systemd service
  service:
    name: etcd
    enabled: yes