- name: Copy binary
  copy: 
    src: downloads/flanneld
    dest: /usr/bin
    mode: 0755

- name: Add systemd service
  template: 
    src: flannel.service.j2
    dest: /etc/systemd/system/flannel.service
    mode: 0644

- name: Enable systemd service
  service:
    name: flannel
    enabled: yes