- name: Disable swapfile
  shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    update-rc.d dphys-swapfile remove
  when: ansible_swaptotal_mb > 0

- name: Disable swapfile service
  service:
    name: dphys-swapfile
    enabled: no

- name: Read kernel command line parameters
  command: cat /boot/cmdline.txt
  register: cmdline
  changed_when: False

- name: Add kernel command line parameters
  when: cmdline.stdout.find(item) == -1
  replace:
    path: /boot/cmdline.txt
    regexp: $
    replace: " {{ item }}"
  with_items:
    - cgroup_enable=cpuset
    - cgroup_enable=memory
    - cgroup_memory=1

- name: Install conntrack from apt
  apt:
    name: conntrack
    update_cache: yes

- delegate_to: localhost
  run_once: true
  become: false
  block:
    - name: Create download directory
      file:
        state: directory
        dest: "{{ role_path }}/files/downloads"

    - name: Download kubernetes server binaries
      get_url:
        url: https://dl.k8s.io/{{ kubernetes_version }}/kubernetes-server-linux-arm.tar.gz
        dest: "{{ role_path }}/files/downloads/kubernetes-server-linux-arm-{{ kubernetes_version }}.tar.gz"

    - name: Extract kubelet and kube-proxy
      command: tar -xf kubernetes-server-linux-arm-{{ kubernetes_version }}.tar.gz --wildcards '*{{ item }}' --transform 's/.*{{ item }}/{{ item }}-{{ kubernetes_version }}/'
      args:
        chdir: "{{ role_path }}/files/downloads"
        creates: "{{ item }}-{{ kubernetes_version }}"
        warn: false
      with_items:
        - kubelet
        - kube-proxy

- name: Copy kubelet and kube-proxy
  copy:
    src: downloads/{{ item }}-{{ kubernetes_version }}
    dest: /usr/bin/{{ item }}
    mode: 0755
  with_items:
    - kubelet
    - kube-proxy

- name: Add kubelet and kube-proxy systemd services
  copy: 
    src: "{{ item }}"
    dest: /etc/systemd/system
    mode: 0644
  with_items:
    - kubelet.service
    - kube-proxy.service

- name: Enable kubelet and kube-proxy systemd services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - kubelet
    - kube-proxy

- name: Reload systemd units
  systemd:
    daemon_reload: yes

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/kubernetes/manifests
    - /etc/kubernetes/kubelet
    - /etc/kubernetes/kube-proxy

- name: Copy kubelet config
  template:
    src: kubelet-config.yml.j2
    dest: /etc/kubernetes/kubelet/config.yml
    mode: 0644