- name: Disable swapfile
  shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    update-rc.d dphys-swapfile remove
  when: ansible_swaptotal_mb > 0

- name: Disable swapfile service
  service:
    name: "{{ item }}"
    enabled: no
  with_items:
    - dphys-swapfile

- name: Read kernel command line parameters
  shell: cat /boot/cmdline.txt
  register: cmdline
  changed_when: False

- name: Add kernel command line parameters
  when: cmdline.stdout.find(item) == -1
  replace:
    path: /boot/cmdline.txt
    regexp: $
    replace: " {{ item }}"
  with_items:
    - cgroup_enable=cpuset
    - cgroup_enable=memory
    - cgroup_memory=1

- name: Install conntrack from apt
  apt:
    name: conntrack
    update_cache: yes

- name: Copy hyperkube binary
  copy: 
    src: downloads/hyperkube
    dest: /usr/bin
    mode: 0755

- name: Add kubelet and kube-proxy systemd services
  copy: 
    src: "{{ item }}"
    dest: /etc/systemd/system
    mode: 0644
  with_items:
    - kubelet.service
    - kube-proxy.service

- name: Enable kubelet and kube-proxy systemd services
  service:
    name: "{{ item }}"
    enabled: yes
  with_items:
    - kubelet
    - kube-proxy

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/kubernetes/manifests
    - /etc/kubernetes/kubelet
    - /etc/kubernetes/kube-proxy

- name: Copy kubelet config
  template:
    src: kubelet-config.yml.j2
    dest: /etc/kubernetes/kubelet/config.yml
    mode: 0644