- name: Add apt signing key for docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg

- name: Add docker repository to apt sources
  apt_repository:
    filename: docker
    repo: deb [arch=armhf] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable

- name: Install from apt
  apt:
    name: docker-ce={{ docker_version }}
    install_recommends: no
    update_cache: yes