- name: Copy kubectl binary
  copy: 
    src: downloads/kubectl
    dest: /usr/bin
    mode: 0755

- name: Create home directory for kubectl
  file:
    path: /root/.kube
    state: directory

- name: Copy kubeconfig
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: kubeconfig.yml, dest: /etc/kubernetes/kubelet-kubeconfig.yml }
    - { src: kubeconfig.yml, dest: /root/.kube/config }

- name: Generate rsa private key for tls certificate
  shell: openssl genrsa -out /etc/kubernetes/apiserver.key
  args:
    creates: /etc/kubernetes/apiserver.key

- name: Copy config file for generating csr
  template:
    src: csr.conf.j2
    dest: /etc/kubernetes/csr.conf
    mode: 0644

- name: Generate tls certificate
  shell: |
    openssl req -new -key apiserver.key -out apiserver.csr -config csr.conf
    openssl x509 -req -in apiserver.csr -CA /etc/ssl/certs/ca.crt -CAkey /etc/ssl/private/ca.key -CAcreateserial -out apiserver.crt -days 10000 -extensions v3_ext -extfile csr.conf
  args:
    chdir: /etc/kubernetes
    creates: /etc/kubernetes/apiserver.crt

- name: Generate rsa private key for service accounts
  shell: openssl genrsa -out /etc/kubernetes/service-accounts-private.pem
  args:
    creates: /etc/kubernetes/service-accounts-private.pem

- name: Generate rsa public key for service accounts
  shell: openssl rsa -in /etc/kubernetes/service-accounts-private.pem -outform PEM -pubout -out /etc/kubernetes/service-accounts-public.pem
  args:
    creates: /etc/kubernetes/service-accounts-public.pem

- name: Copy pods and tokens
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: known-tokens.csv.j2, dest: /etc/kubernetes/known-tokens.csv, mode: "600" }
    - { src: kube-apiserver.json.j2, dest: /etc/kubernetes/manifests/kube-apiserver.json, mode: "644" }
    - { src: kube-controller-manager.json.j2, dest: /etc/kubernetes/manifests/kube-controller-manager.json, mode: "644" }
    - { src: kube-scheduler.json.j2, dest: /etc/kubernetes/manifests/kube-scheduler.json, mode: "644" }